spring:
  application:
    name: reserva-cinema

  datasource:
    url: jdbc:postgresql://localhost:5435/app_db
    username: app_user
    password: app_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true